/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_LE_acceuil_gma (void)
{
  GtkWidget *LE_acceuil_gma;
  GtkWidget *alignment17;
  GtkWidget *eventbox1;
  GtkWidget *fixed1;
  GtkWidget *button_md_gma;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *button_aj_gma;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *button_sup_gma;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *button_vo_gma;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image5;
  GtkWidget *label6;
  GtkWidget *button_findliste_gma;
  GtkWidget *alignment18;
  GtkWidget *hbox17;
  GtkWidget *image16;
  GtkWidget *label18;
  GtkWidget *button1_quitte_gma;
  GtkWidget *alignment19;
  GtkWidget *hbox18;
  GtkWidget *image17;
  GtkWidget *label19;
  GtkWidget *button2_retour_gma;
  GtkWidget *alignment20;
  GtkWidget *hbox19;
  GtkWidget *image18;
  GtkWidget *label20;
  GtkWidget *label17_bnj_gma;

  LE_acceuil_gma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (LE_acceuil_gma), _("window1"));

  alignment17 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (LE_acceuil_gma), alignment17);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (alignment17), eventbox1);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (eventbox1), fixed1);

  button_md_gma = gtk_button_new ();
  gtk_widget_show (button_md_gma);
  gtk_fixed_put (GTK_FIXED (fixed1), button_md_gma, 216, 160);
  gtk_widget_set_size_request (button_md_gma, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_md_gma), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox3), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  button_aj_gma = gtk_button_new ();
  gtk_widget_show (button_aj_gma);
  gtk_fixed_put (GTK_FIXED (fixed1), button_aj_gma, 48, 160);
  gtk_widget_set_size_request (button_aj_gma, 104, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_aj_gma), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox2), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  button_sup_gma = gtk_button_new ();
  gtk_widget_show (button_sup_gma);
  gtk_fixed_put (GTK_FIXED (fixed1), button_sup_gma, 384, 160);
  gtk_widget_set_size_request (button_sup_gma, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_sup_gma), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox4), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  button_vo_gma = gtk_button_new ();
  gtk_widget_show (button_vo_gma);
  gtk_fixed_put (GTK_FIXED (fixed1), button_vo_gma, 216, 264);
  gtk_widget_set_size_request (button_vo_gma, 104, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_vo_gma), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image5 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox6), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Voter"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  button_findliste_gma = gtk_button_new ();
  gtk_widget_show (button_findliste_gma);
  gtk_fixed_put (GTK_FIXED (fixed1), button_findliste_gma, 216, 360);
  gtk_widget_set_size_request (button_findliste_gma, 114, 37);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (button_findliste_gma), alignment18);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox17);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox17), image16, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox17), label18, FALSE, FALSE, 0);

  button1_quitte_gma = gtk_button_new ();
  gtk_widget_show (button1_quitte_gma);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_quitte_gma, 408, 16);
  gtk_widget_set_size_request (button1_quitte_gma, 90, 37);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button1_quitte_gma), alignment19);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox18);

  image17 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox18), image17, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Quiter"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox18), label19, FALSE, FALSE, 0);

  button2_retour_gma = gtk_button_new ();
  gtk_widget_show (button2_retour_gma);
  gtk_fixed_put (GTK_FIXED (fixed1), button2_retour_gma, 40, 16);
  gtk_widget_set_size_request (button2_retour_gma, 88, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button2_retour_gma), alignment20);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox19);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox19), image18, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox19), label20, FALSE, FALSE, 0);

  label17_bnj_gma = gtk_label_new (_("BONJOUR ET BIENVENUE"));
  gtk_widget_show (label17_bnj_gma);
  gtk_fixed_put (GTK_FIXED (fixed1), label17_bnj_gma, 160, 32);
  gtk_widget_set_size_request (label17_bnj_gma, 224, 48);

  g_signal_connect ((gpointer) button_md_gma, "clicked",
                    G_CALLBACK (on_button_md_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_aj_gma, "clicked",
                    G_CALLBACK (on_button_aj_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_sup_gma, "clicked",
                    G_CALLBACK (on_button_sup_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_vo_gma, "clicked",
                    G_CALLBACK (on_button_vo_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_findliste_gma, "clicked",
                    G_CALLBACK (on_button_findliste_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_quitte_gma, "clicked",
                    G_CALLBACK (on_button1_quitte_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_retour_gma, "clicked",
                    G_CALLBACK (on_button2_retour_gma_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LE_acceuil_gma, LE_acceuil_gma, "LE_acceuil_gma");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, button_md_gma, "button_md_gma");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, image2, "image2");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, label3, "label3");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, button_aj_gma, "button_aj_gma");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, image1, "image1");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, label2, "label2");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, button_sup_gma, "button_sup_gma");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, image3, "image3");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, label4, "label4");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, button_vo_gma, "button_vo_gma");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, image5, "image5");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, label6, "label6");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, button_findliste_gma, "button_findliste_gma");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, image16, "image16");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, label18, "label18");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, button1_quitte_gma, "button1_quitte_gma");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, image17, "image17");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, label19, "label19");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, button2_retour_gma, "button2_retour_gma");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, image18, "image18");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, label20, "label20");
  GLADE_HOOKUP_OBJECT (LE_acceuil_gma, label17_bnj_gma, "label17_bnj_gma");

  return LE_acceuil_gma;
}

GtkWidget*
create_LE_pagevote_gma (void)
{
  GtkWidget *LE_pagevote_gma;
  GtkWidget *fixed2;
  GtkObject *spinbutton_num_gma_adj;
  GtkWidget *spinbutton_num_gma;
  GtkWidget *entry1_gma;
  GtkWidget *label32_gma;
  GtkWidget *label44_gma;
  GtkWidget *label42_gma;
  GtkWidget *label1_gma;
  GtkWidget *label1_com_gma;
  GtkWidget *button_vote_gma;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image6;
  GtkWidget *label7;
  GtkWidget *button_ac_gma;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image7;
  GtkWidget *label8;

  LE_pagevote_gma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (LE_pagevote_gma), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (LE_pagevote_gma), fixed2);

  spinbutton_num_gma_adj = gtk_adjustment_new (-1, -1, 25, 1, 10, 10);
  spinbutton_num_gma = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_num_gma_adj), 1, 0);
  gtk_widget_show (spinbutton_num_gma);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_num_gma, 384, 184);
  gtk_widget_set_size_request (spinbutton_num_gma, 56, 24);

  entry1_gma = gtk_entry_new ();
  gtk_widget_show (entry1_gma);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1_gma, 232, 104);
  gtk_widget_set_size_request (entry1_gma, 136, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_gma), 8226);

  label32_gma = gtk_label_new (_("Bienvenue \303\240 l'espace vote"));
  gtk_widget_show (label32_gma);
  gtk_fixed_put (GTK_FIXED (fixed2), label32_gma, 192, 8);
  gtk_widget_set_size_request (label32_gma, 192, 48);
  gtk_label_set_single_line_mode (GTK_LABEL (label32_gma), TRUE);

  label44_gma = gtk_label_new (_("Numero de bureau de vote"));
  gtk_widget_show (label44_gma);
  gtk_fixed_put (GTK_FIXED (fixed2), label44_gma, 16, 104);
  gtk_widget_set_size_request (label44_gma, 184, 40);

  label42_gma = gtk_label_new ("");
  gtk_widget_show (label42_gma);
  gtk_fixed_put (GTK_FIXED (fixed2), label42_gma, 64, 280);
  gtk_widget_set_size_request (label42_gma, 416, 88);

  label1_gma = gtk_label_new (_("Choisir le numero de la liste \303\240 voter"));
  gtk_widget_show (label1_gma);
  gtk_fixed_put (GTK_FIXED (fixed2), label1_gma, 8, 184);
  gtk_widget_set_size_request (label1_gma, 264, 24);

  label1_com_gma = gtk_label_new (_("Selectionnez -1 pour aucun vote"));
  gtk_widget_show (label1_com_gma);
  gtk_fixed_put (GTK_FIXED (fixed2), label1_com_gma, 8, 224);
  gtk_widget_set_size_request (label1_com_gma, 240, 32);

  button_vote_gma = gtk_button_new ();
  gtk_widget_show (button_vote_gma);
  gtk_fixed_put (GTK_FIXED (fixed2), button_vote_gma, 368, 216);
  gtk_widget_set_size_request (button_vote_gma, 96, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_vote_gma), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image6 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox7), image6, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("voter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox7), label7, FALSE, FALSE, 0);

  button_ac_gma = gtk_button_new ();
  gtk_widget_show (button_ac_gma);
  gtk_fixed_put (GTK_FIXED (fixed2), button_ac_gma, 24, 8);
  gtk_widget_set_size_request (button_ac_gma, 152, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_ac_gma), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image7 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox8), image7, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Page d'accueil"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox8), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_vote_gma, "clicked",
                    G_CALLBACK (on_button_vote_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ac_gma, "clicked",
                    G_CALLBACK (on_button_ac_gma_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LE_pagevote_gma, LE_pagevote_gma, "LE_pagevote_gma");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, spinbutton_num_gma, "spinbutton_num_gma");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, entry1_gma, "entry1_gma");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, label32_gma, "label32_gma");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, label44_gma, "label44_gma");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, label42_gma, "label42_gma");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, label1_gma, "label1_gma");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, label1_com_gma, "label1_com_gma");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, button_vote_gma, "button_vote_gma");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, image6, "image6");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, label7, "label7");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, button_ac_gma, "button_ac_gma");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, image7, "image7");
  GLADE_HOOKUP_OBJECT (LE_pagevote_gma, label8, "label8");

  return LE_pagevote_gma;
}

GtkWidget*
create_Le_Pajout_gma (void)
{
  GtkWidget *Le_Pajout_gma;
  GtkWidget *fixed3;
  GtkWidget *entry_m3_gma;
  GtkWidget *entry_idt_gma;
  GtkWidget *entry_m1_gma;
  GtkWidget *entry_m2_gma;
  GtkWidget *entry_idl_gma;
  GtkWidget *radiobutton2_ce;
  GSList *radiobutton2_ce_group = NULL;
  GtkWidget *label38_gma;
  GtkWidget *radiobutton3_dr;
  GtkWidget *label_gma;
  GtkWidget *label8_gma;
  GtkWidget *radiobutton1_ga;
  GtkWidget *label4_gma;
  GtkWidget *label7_gma;
  GtkWidget *label6_gma;
  GtkWidget *label37_gma;
  GtkWidget *button_ac_gma;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image8;
  GtkWidget *label9;
  GtkWidget *button_save_gma;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image10;
  GtkWidget *label11;

  Le_Pajout_gma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Le_Pajout_gma), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Le_Pajout_gma), fixed3);

  entry_m3_gma = gtk_entry_new ();
  gtk_widget_show (entry_m3_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_m3_gma, 224, 464);
  gtk_widget_set_size_request (entry_m3_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_m3_gma), 8226);

  entry_idt_gma = gtk_entry_new ();
  gtk_widget_show (entry_idt_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_idt_gma, 224, 160);
  gtk_widget_set_size_request (entry_idt_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idt_gma), 8226);

  entry_m1_gma = gtk_entry_new ();
  gtk_widget_show (entry_m1_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_m1_gma, 224, 352);
  gtk_widget_set_size_request (entry_m1_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_m1_gma), 8226);

  entry_m2_gma = gtk_entry_new ();
  gtk_widget_show (entry_m2_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_m2_gma, 224, 408);
  gtk_widget_set_size_request (entry_m2_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_m2_gma), 8226);

  entry_idl_gma = gtk_entry_new ();
  gtk_widget_show (entry_idl_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_idl_gma, 224, 96);
  gtk_widget_set_size_request (entry_idl_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idl_gma), 8226);

  radiobutton2_ce = gtk_radio_button_new_with_mnemonic (NULL, _("centre"));
  gtk_widget_show (radiobutton2_ce);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton2_ce, 232, 256);
  gtk_widget_set_size_request (radiobutton2_ce, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_ce), radiobutton2_ce_group);
  radiobutton2_ce_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_ce));

  label38_gma = gtk_label_new (_("oriontation"));
  gtk_widget_show (label38_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), label38_gma, 184, 216);
  gtk_widget_set_size_request (label38_gma, 184, 24);

  radiobutton3_dr = gtk_radio_button_new_with_mnemonic (NULL, _("droite"));
  gtk_widget_show (radiobutton3_dr);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton3_dr, 376, 256);
  gtk_widget_set_size_request (radiobutton3_dr, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3_dr), radiobutton2_ce_group);
  radiobutton2_ce_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3_dr));

  label_gma = gtk_label_new (_("ID Tete"));
  gtk_widget_show (label_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), label_gma, 24, 160);
  gtk_widget_set_size_request (label_gma, 128, 32);

  label8_gma = gtk_label_new (_("ID liste"));
  gtk_widget_show (label8_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), label8_gma, 24, 96);
  gtk_widget_set_size_request (label8_gma, 128, 32);

  radiobutton1_ga = gtk_radio_button_new_with_mnemonic (NULL, _("gauche"));
  gtk_widget_show (radiobutton1_ga);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton1_ga, 88, 256);
  gtk_widget_set_size_request (radiobutton1_ga, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_ga), radiobutton2_ce_group);
  radiobutton2_ce_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_ga));

  label4_gma = gtk_label_new (_("ID membre "));
  gtk_widget_show (label4_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), label4_gma, 48, 344);
  gtk_widget_set_size_request (label4_gma, 128, 32);

  label7_gma = gtk_label_new (_("ID membre "));
  gtk_widget_show (label7_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), label7_gma, 48, 408);
  gtk_widget_set_size_request (label7_gma, 128, 32);

  label6_gma = gtk_label_new (_("ID membre "));
  gtk_widget_show (label6_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), label6_gma, 48, 464);
  gtk_widget_set_size_request (label6_gma, 128, 32);

  label37_gma = gtk_label_new ("");
  gtk_widget_show (label37_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), label37_gma, 208, 16);
  gtk_widget_set_size_request (label37_gma, 248, 64);

  button_ac_gma = gtk_button_new ();
  gtk_widget_show (button_ac_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), button_ac_gma, 32, 16);
  gtk_widget_set_size_request (button_ac_gma, 152, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_ac_gma), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image8 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox9), image8, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Page d'accueil"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox9), label9, FALSE, FALSE, 0);

  button_save_gma = gtk_button_new ();
  gtk_widget_show (button_save_gma);
  gtk_fixed_put (GTK_FIXED (fixed3), button_save_gma, 264, 512);
  gtk_widget_set_size_request (button_save_gma, 120, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_save_gma), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox11), image10, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox11), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton2_ce, "toggled",
                    G_CALLBACK (on_radiobutton2_ce_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3_dr, "toggled",
                    G_CALLBACK (on_radiobutton3_dr_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_ga, "toggled",
                    G_CALLBACK (on_radiobutton1_ga_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ac_gma, "clicked",
                    G_CALLBACK (on_button_ac_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_save_gma, "clicked",
                    G_CALLBACK (on_button_save_gma_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Le_Pajout_gma, Le_Pajout_gma, "Le_Pajout_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, entry_m3_gma, "entry_m3_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, entry_idt_gma, "entry_idt_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, entry_m1_gma, "entry_m1_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, entry_m2_gma, "entry_m2_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, entry_idl_gma, "entry_idl_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, radiobutton2_ce, "radiobutton2_ce");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, label38_gma, "label38_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, radiobutton3_dr, "radiobutton3_dr");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, label_gma, "label_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, label8_gma, "label8_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, radiobutton1_ga, "radiobutton1_ga");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, label4_gma, "label4_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, label7_gma, "label7_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, label6_gma, "label6_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, label37_gma, "label37_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, button_ac_gma, "button_ac_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, image8, "image8");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, label9, "label9");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, button_save_gma, "button_save_gma");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, image10, "image10");
  GLADE_HOOKUP_OBJECT (Le_Pajout_gma, label11, "label11");

  return Le_Pajout_gma;
}

GtkWidget*
create_LE_Pmodifier_gma (void)
{
  GtkWidget *LE_Pmodifier_gma;
  GtkWidget *fixed4;
  GtkWidget *entry_m3m_gma;
  GtkWidget *entry_idtm_gma;
  GtkWidget *entry_m1m_gma;
  GtkWidget *entry_m2m_gma;
  GtkWidget *entry_idlm_gma;
  GtkWidget *radiobutton_md_gma;
  GSList *radiobutton_md_gma_group = NULL;
  GtkWidget *radiobutton_mc_gma;
  GtkWidget *radiobutton_mg_gma;
  GtkWidget *label13_gma;
  GtkWidget *label12_gma;
  GtkWidget *label11_gma;
  GtkWidget *label10_gma;
  GtkWidget *label9_gma;
  GtkWidget *label39_gma;
  GtkWidget *button_ac_gma;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image9;
  GtkWidget *label10;
  GtkWidget *label40_gma;
  GtkWidget *button_modi_gma;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image11;
  GtkWidget *label12;

  LE_Pmodifier_gma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (LE_Pmodifier_gma, 0, 500);
  gtk_window_set_title (GTK_WINDOW (LE_Pmodifier_gma), _("window3"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (LE_Pmodifier_gma), fixed4);

  entry_m3m_gma = gtk_entry_new ();
  gtk_widget_show (entry_m3m_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_m3m_gma, 216, 440);
  gtk_widget_set_size_request (entry_m3m_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_m3m_gma), 8226);

  entry_idtm_gma = gtk_entry_new ();
  gtk_widget_show (entry_idtm_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_idtm_gma, 224, 160);
  gtk_widget_set_size_request (entry_idtm_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idtm_gma), 8226);

  entry_m1m_gma = gtk_entry_new ();
  gtk_widget_show (entry_m1m_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_m1m_gma, 216, 328);
  gtk_widget_set_size_request (entry_m1m_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_m1m_gma), 8226);

  entry_m2m_gma = gtk_entry_new ();
  gtk_widget_show (entry_m2m_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_m2m_gma, 216, 384);
  gtk_widget_set_size_request (entry_m2m_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_m2m_gma), 8226);

  entry_idlm_gma = gtk_entry_new ();
  gtk_widget_show (entry_idlm_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_idlm_gma, 224, 96);
  gtk_widget_set_size_request (entry_idlm_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idlm_gma), 8226);

  radiobutton_md_gma = gtk_radio_button_new_with_mnemonic (NULL, _("droite"));
  gtk_widget_show (radiobutton_md_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_md_gma, 344, 248);
  gtk_widget_set_size_request (radiobutton_md_gma, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_md_gma), radiobutton_md_gma_group);
  radiobutton_md_gma_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_md_gma));

  radiobutton_mc_gma = gtk_radio_button_new_with_mnemonic (NULL, _("centre"));
  gtk_widget_show (radiobutton_mc_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_mc_gma, 200, 248);
  gtk_widget_set_size_request (radiobutton_mc_gma, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mc_gma), radiobutton_md_gma_group);
  radiobutton_md_gma_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mc_gma));

  radiobutton_mg_gma = gtk_radio_button_new_with_mnemonic (NULL, _("gauche"));
  gtk_widget_show (radiobutton_mg_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_mg_gma, 80, 248);
  gtk_widget_set_size_request (radiobutton_mg_gma, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mg_gma), radiobutton_md_gma_group);
  radiobutton_md_gma_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mg_gma));

  label13_gma = gtk_label_new (_("ID liste"));
  gtk_widget_show (label13_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), label13_gma, 24, 96);
  gtk_widget_set_size_request (label13_gma, 128, 32);

  label12_gma = gtk_label_new (_("ID Tete"));
  gtk_widget_show (label12_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), label12_gma, 24, 160);
  gtk_widget_set_size_request (label12_gma, 128, 32);

  label11_gma = gtk_label_new (_("ID membre "));
  gtk_widget_show (label11_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), label11_gma, 40, 320);
  gtk_widget_set_size_request (label11_gma, 128, 32);

  label10_gma = gtk_label_new (_("ID membre "));
  gtk_widget_show (label10_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), label10_gma, 40, 384);
  gtk_widget_set_size_request (label10_gma, 128, 32);

  label9_gma = gtk_label_new (_("ID membre "));
  gtk_widget_show (label9_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), label9_gma, 40, 432);
  gtk_widget_set_size_request (label9_gma, 128, 32);

  label39_gma = gtk_label_new (_("oriontation"));
  gtk_widget_show (label39_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), label39_gma, 152, 208);
  gtk_widget_set_size_request (label39_gma, 224, 32);

  button_ac_gma = gtk_button_new ();
  gtk_widget_show (button_ac_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), button_ac_gma, 32, 16);
  gtk_widget_set_size_request (button_ac_gma, 152, 40);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_ac_gma), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image9 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox10), image9, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Page d'accueil"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox10), label10, FALSE, FALSE, 0);

  label40_gma = gtk_label_new ("");
  gtk_widget_show (label40_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), label40_gma, 208, 16);
  gtk_widget_set_size_request (label40_gma, 240, 64);

  button_modi_gma = gtk_button_new ();
  gtk_widget_show (button_modi_gma);
  gtk_fixed_put (GTK_FIXED (fixed4), button_modi_gma, 240, 496);
  gtk_widget_set_size_request (button_modi_gma, 120, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_modi_gma), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox12), image11, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox12), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton_md_gma, "toggled",
                    G_CALLBACK (on_radiobutton_md_gma_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mc_gma, "toggled",
                    G_CALLBACK (on_radiobutton_mc_gma_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mg_gma, "toggled",
                    G_CALLBACK (on_radiobutton_mg_gma_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ac_gma, "clicked",
                    G_CALLBACK (on_button_ac_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modi_gma, "clicked",
                    G_CALLBACK (on_button_modi_gma_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LE_Pmodifier_gma, LE_Pmodifier_gma, "LE_Pmodifier_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, entry_m3m_gma, "entry_m3m_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, entry_idtm_gma, "entry_idtm_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, entry_m1m_gma, "entry_m1m_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, entry_m2m_gma, "entry_m2m_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, entry_idlm_gma, "entry_idlm_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, radiobutton_md_gma, "radiobutton_md_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, radiobutton_mc_gma, "radiobutton_mc_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, radiobutton_mg_gma, "radiobutton_mg_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, label13_gma, "label13_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, label12_gma, "label12_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, label11_gma, "label11_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, label10_gma, "label10_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, label9_gma, "label9_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, label39_gma, "label39_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, button_ac_gma, "button_ac_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, image9, "image9");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, label10, "label10");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, label40_gma, "label40_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, button_modi_gma, "button_modi_gma");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, image11, "image11");
  GLADE_HOOKUP_OBJECT (LE_Pmodifier_gma, label12, "label12");

  return LE_Pmodifier_gma;
}

GtkWidget*
create_LE_Psupp_gma (void)
{
  GtkWidget *LE_Psupp_gma;
  GtkWidget *fixed5;
  GtkWidget *entry_idlsupp_gma;
  GtkWidget *label20_gma;
  GtkWidget *button_supp_gma;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image12;
  GtkWidget *label13;
  GtkWidget *label41_gma;
  GtkWidget *button_ac_gma;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image13;
  GtkWidget *label14;

  LE_Psupp_gma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (LE_Psupp_gma), _("window3"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (LE_Psupp_gma), fixed5);

  entry_idlsupp_gma = gtk_entry_new ();
  gtk_widget_show (entry_idlsupp_gma);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_idlsupp_gma, 168, 112);
  gtk_widget_set_size_request (entry_idlsupp_gma, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idlsupp_gma), 8226);

  label20_gma = gtk_label_new (_("ID liste"));
  gtk_widget_show (label20_gma);
  gtk_fixed_put (GTK_FIXED (fixed5), label20_gma, 64, 112);
  gtk_widget_set_size_request (label20_gma, 128, 32);

  button_supp_gma = gtk_button_new ();
  gtk_widget_show (button_supp_gma);
  gtk_fixed_put (GTK_FIXED (fixed5), button_supp_gma, 216, 232);
  gtk_widget_set_size_request (button_supp_gma, 128, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_supp_gma), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image12 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox13), image12, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox13), label13, FALSE, FALSE, 0);

  label41_gma = gtk_label_new ("");
  gtk_widget_show (label41_gma);
  gtk_fixed_put (GTK_FIXED (fixed5), label41_gma, 200, 16);
  gtk_widget_set_size_request (label41_gma, 232, 56);

  button_ac_gma = gtk_button_new ();
  gtk_widget_show (button_ac_gma);
  gtk_fixed_put (GTK_FIXED (fixed5), button_ac_gma, 32, 16);
  gtk_widget_set_size_request (button_ac_gma, 144, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_ac_gma), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image13 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox14), image13, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Page d'accueil"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox14), label14, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_supp_gma, "clicked",
                    G_CALLBACK (on_button_supp_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ac_gma, "clicked",
                    G_CALLBACK (on_button_ac_gma_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LE_Psupp_gma, LE_Psupp_gma, "LE_Psupp_gma");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, entry_idlsupp_gma, "entry_idlsupp_gma");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, label20_gma, "label20_gma");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, button_supp_gma, "button_supp_gma");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, image12, "image12");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, label13, "label13");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, label41_gma, "label41_gma");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, button_ac_gma, "button_ac_gma");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, image13, "image13");
  GLADE_HOOKUP_OBJECT (LE_Psupp_gma, label14, "label14");

  return LE_Psupp_gma;
}

GtkWidget*
create_LE_recherche_gma (void)
{
  GtkWidget *LE_recherche_gma;
  GtkWidget *fixed6;
  GtkWidget *treeview2_gma;
  GtkWidget *button_ac_gma;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image14;
  GtkWidget *label15;
  GtkWidget *button1_ref_gma;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image15;
  GtkWidget *label16;
  GtkWidget *label43_gma;

  LE_recherche_gma = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (LE_recherche_gma), _("LE_recherche_gma"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (LE_recherche_gma), fixed6);

  treeview2_gma = gtk_tree_view_new ();
  gtk_widget_show (treeview2_gma);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview2_gma, 96, 96);
  gtk_widget_set_size_request (treeview2_gma, 384, 248);

  button_ac_gma = gtk_button_new ();
  gtk_widget_show (button_ac_gma);
  gtk_fixed_put (GTK_FIXED (fixed6), button_ac_gma, 112, 368);
  gtk_widget_set_size_request (button_ac_gma, 136, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_ac_gma), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image14 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox15), image14, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Page d'accueil"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox15), label15, FALSE, FALSE, 0);

  button1_ref_gma = gtk_button_new ();
  gtk_widget_show (button1_ref_gma);
  gtk_fixed_put (GTK_FIXED (fixed6), button1_ref_gma, 264, 368);
  gtk_widget_set_size_request (button1_ref_gma, 128, 48);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button1_ref_gma), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image15 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox16), image15, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox16), label16, FALSE, FALSE, 0);

  label43_gma = gtk_label_new (_("Bienvenue vous trouvez votre liste ici"));
  gtk_widget_show (label43_gma);
  gtk_fixed_put (GTK_FIXED (fixed6), label43_gma, 120, 40);
  gtk_widget_set_size_request (label43_gma, 328, 32);

  g_signal_connect ((gpointer) treeview2_gma, "row_activated",
                    G_CALLBACK (on_treeview2_gma_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_ac_gma, "clicked",
                    G_CALLBACK (on_button_ac_gma_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_ref_gma, "clicked",
                    G_CALLBACK (on_button1_ref_gma_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (LE_recherche_gma, LE_recherche_gma, "LE_recherche_gma");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, treeview2_gma, "treeview2_gma");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, button_ac_gma, "button_ac_gma");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, image14, "image14");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, label15, "label15");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, button1_ref_gma, "button1_ref_gma");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, image15, "image15");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, label16, "label16");
  GLADE_HOOKUP_OBJECT (LE_recherche_gma, label43_gma, "label43_gma");

  return LE_recherche_gma;
}

