/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_LE_acceuil_gma (void);
GtkWidget* create_LE_pagevote_gma (void);
GtkWidget* create_Le_Pajout_gma (void);
GtkWidget* create_LE_Pmodifier_gma (void);
GtkWidget* create_LE_Psupp_gma (void);
