/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Ajout_gest_Utilis (void);
GtkWidget* create_Modifie_gest_Utilis (void);
GtkWidget* create_Supprimer_gest_Utilis (void);
GtkWidget* create_Gestion_Utilisateur (void);
GtkWidget* create_Connexion (void);
GtkWidget* create_Menu (void);
GtkWidget* create_LE_acceuil_gma (void);
GtkWidget* create_LE_pagevote_gma (void);
GtkWidget* create_Le_Pajout_gma (void);
GtkWidget* create_LE_Pmodifier_gma (void);
GtkWidget* create_LE_Psupp_gma (void);
GtkWidget* create_LE_recherche_gma (void);
